apiVersion: v1
kind: Service
metadata:
  name: user-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for StatefulSet DNS
  selector:
    app: user-postgres