apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: NodePort
  selector:
    app: apigateway-service
  ports:
    - port: 80             # External port (what users hit)
      targetPort: 8080     # Container port (Spring Boot app)
      nodePort: 30081      # Fixed port exposed by the node
