#server:
#  port: 8081
#
#spring:
#  application:
#    name: user-app
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: password
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
server:
  port: 8081

spring:
  application:
    name: user-app
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
        host: ${REDIS_HOST:redis}
        port: 6379
        database: 0  # Explicitly set DB index

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
