apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: mouradgalal/user-app:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_REDIS_HOST
              value: redis-service
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: HOST_NAME
              value: "127.0.0.1"   # Kubernetes service DNS or External IP
---
apiVersion: v1
kind: Service
metadata:
  name: user-app
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081  # External port on the Node