apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-checkout
spec:
  serviceName: "postgres-checkout"  # must match headless service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-checkout
  template:
    metadata:
      labels:
        app: postgres-checkout
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: checkoutdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: checkout-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: checkout-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
